// fsm
export const FSM_NAME_CHANGED = 'FSM_NAME_CHANGED';
export const FSM_STATES_CHANGED = 'FSM_STATES_CHANGED';
export const FSM_ALPHABET_CHANGED = 'FSM_ALPHABET_CHANGED';
export const FSM_STATE_MOVED = 'FSM_STATE_MOVED';
export const FSM_STATE_ADDED = 'FSM_STATE_ADDED';
export const FSM_STATE_SELECTED = 'FSM_STATE_SELECTED';
export const FSM_STATE_NAME_CHANGED = 'FSM_STATE_NAME_CHANGED';
export const FSM_STATE_DELETED = 'FSM_STATE_DELETED';
export const FSM_INITIAL_STATE_CHANGED = 'FSM_INITIAL_STATE_CHANGED';
export const FSM_INITIAL_STATE_REMOVED = 'FSM_INITIAL_STATE_REMOVED';
export const FSM_ACCEPT_STATE_ADDED = 'FSM_ACCEPT_STATE_ADDED';
export const FSM_ACCEPT_STATE_REMOVED = 'FSM_ACCEPT_STATE_REMOVED';
export const FSM_TRANSITION_ADDED = 'FSM_TRANSITION_ADDED';
export const FSM_TRANSITION_REMOVED = 'FSM_TRANSITION_REMOVED';
export const FSM_LETTER_ADDED = 'FSM_LETTER_ADDED';
export const FSM_INITIALIZED_FROM_JSON_STRING = 'FSM_INITIALIZED_FROM_JSON_STRING';

// settings
export const SETTINGS_DARK_THEME_SET = 'SETTINGS_DARK_THEME_SET';