// fsm
export const FSM_NAME_CHANGED = 'FSM_NAME_CHANGED';
export const FSM_STATE_MOVED = 'FSM_STATE_MOVED';
export const FSM_STATE_ADDED = 'FSM_STATE_ADDED';
export const FSM_STATE_SELECTED = 'FSM_STATE_SELECTED';
export const FSM_STATE_NAME_CHANGED = 'FSM_STATE_NAME_CHANGED';
export const FSM_STATE_DELETED = 'FSM_STATE_DELETED';
export const FSM_INITIAL_STATE_CHANGED = 'FSM_INITIAL_STATE_CHANGED';
export const FSM_INITIAL_STATE_REMOVED = 'FSM_INITIAL_STATE_REMOVED';
export const FSM_ACCEPT_STATE_ADDED = 'FSM_ACCEPT_STATE_ADDED';
export const FSM_ACCEPT_STATE_REMOVED = 'FSM_ACCEPT_STATE_REMOVED';
export const FSM_TRANSITION_ADDED = 'FSM_TRANSITION_ADDED';
export const FSM_TRANSITION_REMOVED = 'FSM_TRANSITION_REMOVED';
export const FSM_SYMBOL_ADDED = 'FSM_SYMBOL_ADDED';
export const FSM_INITIALIZED_FROM_JSON_STRING = 'FSM_INITIALIZED_FROM_JSON_STRING';
export const FSM_RESET = 'FSM_RESET';

// pda
export const PDA_NAME_CHANGED = 'PDA_NAME_CHANGED';
export const PDA_STATE_MOVED = 'PDA_STATE_MOVED';
export const PDA_STATE_ADDED = 'PDA_STATE_ADDED';
export const PDA_STATE_SELECTED = 'PDA_STATE_SELECTED';
export const PDA_STATE_NAME_CHANGED = 'PDA_STATE_NAME_CHANGED';
export const PDA_STATE_DELETED = 'PDA_STATE_DELETED';
export const PDA_INITIAL_STATE_CHANGED = 'PDA_INITIAL_STATE_CHANGED';
export const PDA_INITIAL_STATE_REMOVED = 'PDA_INITIAL_STATE_REMOVED';
export const PDA_ACCEPT_STATE_ADDED = 'PDA_ACCEPT_STATE_ADDED';
export const PDA_ACCEPT_STATE_REMOVED = 'PDA_ACCEPT_STATE_REMOVED';
export const PDA_TRANSITION_ADDED = 'PDA_TRANSITION_ADDED';
export const PDA_TRANSITION_REMOVED = 'PDA_TRANSITION_REMOVED';
export const PDA_INPUT_SYMBOL_ADDED = 'PDA_INPUT_SYMBOL_ADDED';
export const PDA_STACK_SYMBOL_ADDED = 'PDA_STACK_SYMBOL_ADDED';
export const PDA_INITIAL_STACK_SYMBOL_CHANGED = 'PDA_INITIAL_STACK_SYMBOL_CHANGED';
export const PDA_INITIAL_STACK_SYMBOL_REMOVED = 'PDA_INITIAL_STACK_SYMBOL_REMOVED';
export const PDA_INITIALIZED_FROM_JSON_STRING = 'PDA_INITIALIZED_FROM_JSON_STRING';
export const PDA_RESET = 'PDA_RESET';

// tm
export const TM_NAME_CHANGED = 'TM_NAME_CHANGED';
export const TM_STATE_MOVED = 'TM_STATE_MOVED';
export const TM_STATE_ADDED = 'TM_STATE_ADDED';
export const TM_STATE_SELECTED = 'TM_STATE_SELECTED';
export const TM_STATE_NAME_CHANGED = 'TM_STATE_NAME_CHANGED';
export const TM_STATE_DELETED = 'TM_STATE_DELETED';
export const TM_INITIAL_STATE_CHANGED = 'TM_INITIAL_STATE_CHANGED';
export const TM_INITIAL_STATE_REMOVED = 'TM_INITIAL_STATE_REMOVED';
export const TM_ACCEPT_STATE_ADDED = 'TM_ACCEPT_STATE_ADDED';
export const TM_ACCEPT_STATE_REMOVED = 'TM_ACCEPT_STATE_REMOVED';
export const TM_TRANSITION_ADDED = 'TM_TRANSITION_ADDED';
export const TM_TRANSITION_REMOVED = 'TM_TRANSITION_REMOVED';
export const TM_TAPE_SYMBOL_ADDED = 'TM_TAPE_SYMBOL_ADDED';
export const TM_INPUT_SYMBOL_ADDED = 'TM_INPUT_SYMBOL_ADDED';
export const TM_BLANK_SYMBOL_CHANGED = 'TM_BLANK_SYMBOL_CHANGED';
export const TM_BLANK_SYMBOL_REMOVED = 'TM_BLANK_SYMBOL_REMOVED';
export const TM_INITIALIZED_FROM_JSON_STRING = 'TM_INITIALIZED_FROM_JSON_STRING';
export const TM_RESET = 'TM_RESET';

// regex
export const REGEX_SET = 'REGEX_SET';
export const REGEX_CLEARED = 'REGEX_CLEARED';

// modal
export const MODAL_CREATED = 'MODAL_CREATED';
export const MODAL_REMOVED = 'MODAL_REMOVED';

// settings
export const SETTINGS_DARK_THEME_SET = 'SETTINGS_DARK_THEME_SET';
export const SETTINGS_EMPTY_STRING_SYMBOL_SET = 'SETTINGS_EMPTY_STRING_SYMBOL_SET';
export const SETTINGS_ALTERNATION_SYMBOL_SET = 'SETTINGS_ALTERNATION_SYMBOL_SET';