export const INITIAL_STATE_MODAL = 'INITIAL_STATE_MODAL';
export const INITIAL_STACK_SYMBOL_MODAL = 'INITIAL_STACK_SYMBOL_MODAL';
export const BLANK_SYMBOL_MODAL = 'BLANK_SYMBOL_MODAL';
export const ACCEPT_STATES_MODAL = 'ACCEPT_STATES_MODAL';
export const INPUT_ALPHABET_MODAL = 'INPUT_ALPHABET_MODAL';